export const RPC_EVENT_NAME = '__RPC_CALL_CLIPSHEET_AWESOME__'
export const RPC_RESPONSE_EVENT_NAME = '__RPC_RESPONSE_CLIPSHEET_AWESOME__'

export const SUBSCRIBABLE_OBSERVABLE = '__SUBSCRIBABLE_OBSERVABLE__'
export const UNSUBSCRIBE_OBSERVABLE = '__UNSUBSCRIBE_OBSERVABLE__'
export const OBSERVABLE_EVENT = '__OBSERVABLE_EVENT__'
