export const RPC_EVENT_NAME = '__RPC_CALL_CRX_RPC__'
export const RPC_PING = '__RPC_PING__'
export const RPC_PONG = '__RPC_PONG__'
export const RPC_RESPONSE_EVENT_NAME = '__RPC_RESPONSE_CRX_RPC__'

export const SUBSCRIBABLE_OBSERVABLE = '__SUBSCRIBABLE_OBSERVABLE__'
export const UNSUBSCRIBE_OBSERVABLE = '__UNSUBSCRIBE_OBSERVABLE__'
export const OBSERVABLE_EVENT = '__OBSERVABLE_EVENT__'
